#!/usr/bin/env bash

set -e

SYSTEM_TYPE=$(lsb_release -s -d | tr -d '"')

if [[ $SYSTEM_TYPE == "Arch Linux" ]]; then
    have ansible || sudo pacman -S ansible

    # Install requirements
    ansible-galaxy install -r ~/.config/ansible/requirements.yml

	# Install System Tools and Configurations
    ansible-playbook -i ~/.config/ansible/inventory ~/.config/ansible/arch.yml --ask-become-pass

elif [[ $SYSTEM_TYPE == "Ubuntu" ]]; then
    have ansible || sudo apt install ansible

    # Install requirements
    ansible-galaxy install -r ~/.config/yadm/requirements.yml

    # Install System Tools and Configurations
    ansible-playbook -i ~/.config/ansible/inventory ~/.config/ansible/ubuntu.yml --ask-become-pass
fi