#!/usr/bin/env bash
set -e

vol_export() {
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "use: $0 export volume file.tar.gz"
        exit 1
    fi
    
    VOLUME="$1"
    FILE="$2"
    
    docker volume inspect "$VOLUME" >/dev/null 2>&1 || {
        echo "volume dont exist"
        exit 1
    }
    
    docker run --rm \
    -v "${VOLUME}:/source:ro" \
    -v "$(pwd):/backup" \
    ubuntu \
    tar czf "/backup/$(basename "$FILE")" -C /source .
}

vol_import() {
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "use: $0 import file.tar.gz volume"
        exit 1
    fi
    
    FILE="$1"
    VOLUME="$2"
    
    [ -f "$FILE" ] || {
        echo "file dont exist"
        exit 1
    }
    
    docker volume inspect "$VOLUME" >/dev/null 2>&1 || {
        docker volume create "$VOLUME"
    }
    
    docker run --rm \
    -v "${VOLUME}:/target" \
    -v "$(pwd):/backup" \
    ubuntu \
    tar xzf "/backup/$(basename "$FILE")" -C /target
}

vol_clone() {
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "use: $0 clone volumen-source volumen-destination"
        exit 1
    fi
    
    SRC="$1"
    DST="$2"
    
    docker volume inspect "$SRC" >/dev/null 2>&1 || {
        echo "volume dont exist"
        exit 1
    }
    
    docker volume inspect "$DST" >/dev/null 2>&1 || {
        docker volume create "$DST"
    }
    
    docker run --rm \
    -v "${SRC}:/source:ro" \
    -v "${DST}:/target" \
    ubuntu \
    cp -a /source/. /target/
}

case "${1:-}" in
    export)
        shift
        vol_export "$@"
    ;;
    import)
        shift
        vol_import "$@"
    ;;
    clone)
        shift
        vol_clone "$@"
    ;;
    *)
        echo "Commands: [export, import, clone]"
        exit 1
    ;;
esac
