#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Use: $0 volume name"
  exit 1
fi

VOLUME="$1"
FILE="${VOLUME}.tar.gz"

docker run --rm \
  -v "${VOLUME}:/source" \
  ubuntu \
  rm -rf /source/* /source/.* 2>/dev/null || true
